language: python

python:
  - "3.8.3"

before_install:
  - pip install poetry

install:
  - pip install coveralls
  - poetry install

script:
  - poetry run pytest

after_success:
  - coverage
  - coveralls
